### PR TITLE
[WIP] citra-qt: add support for gamepad in input configuration window

### PR DESCRIPTION
**Pull request by wwylele**
TODO

- [x] receive hat input
- [x] analog input configuration rework
- [ ] layout rework?
- [ ] `GetDescription` method for `Factory` ?

### CODE REVIEW

**Comment by Jhno591** [comment]
looking good and grate work!, post here test.
any think to confirm are test using this then let us know ?

**Comment by Jhno591** [comment]
Just needs a small re-base to new main citra "configuration" folder
re-work
https://github.com/Jhno591/citra-2/commit/f719bab38a9ead40a2ac15f54d7a96e05ee0feac

**Comment by wwylele** [comment]
about the analog stick binding issue:

wwylele - Today at 8:47 PM
anyway I am probably not going to touch the controller gui within a month, so @jroweboy  feel free to take over it (either continue my branch or start from scratch)
@jroweboy need to note: there are two branches in my repo: input-config-2 and input-config-3. The latter one is rebased against a newer master, but with analog stick binding removed (with which I had problems

jroweboy - Today at 8:52 PM
i was looking at your PR to your own repo based of input-config-2. Whats up with the analog stick binding?

wwylele - Today at 8:53 PM
The original idea of analog stick binding was, like the button binding one, user push the button and move the stick, so that the gui will record the id of the moving stick and bind it
the issues are:
1. Windows has mouse movment registered as axis 9 and 10 :unamused:
2. I can't assume x-axis always has an even id and y-axis has an odd one (xinput is an exception), so  how do I determine which is x and which is y?

jroweboy - Today at 8:56 PM
shouldn't you just ask them to push up and then left? and that should give you +x and +y

wwylele - Today at 8:57 PM
well yeah there are some solutions like this, I am just kind of tired of thinking all the details...
actually I was just pissed off by the first point and lost my enthusiasm :expressionless:

**Comment by Jhno591** [comment]
y+ up , x+ left , b+ right , a+ down well that's how it's mapped by on xbox 360 pad...

**Comment by wwylele** [comment]
(jroweboy is working on this)

**Comment by wwylele** [comment]
I don't need to do this anymore

**Pull request closed without merging**
