### PR TITLE
Correct FS error codes & add path boundary checks

### PR DESCRIPTION
**Pull request by wwylele**
_DRAFT_

The main part of this PR is to fix error codes of archive operations. Because error codes can vary among different error types and archive types, I had to refactor the `ArchiveBackend` interface and their subclass: let all method report its own error code, and split `DiskArchive` into 3 classes `SaveDataArchive`, `ExtSaveDataArchive` and `SDMCArchive`. Sorry for not following the suggestion in the code comment "This should be subclassed by concrete archive types", but if, for example, I let `SaveDataArchive` be a subclass off `DiskArchive`, I will literally override everything due to different error check behaviour, which is effectively the same as making a brand new class.

The error codes were got from [this test program](https://github.com/wwylele/3DS-FS-Tester) and here is [a summary sheet](https://drive.google.com/file/d/0ByjS9HUStkSXUmtPdWdmd25CeGc/view?usp=drivesdk). However, with this PR, citra and real 3DS still don't behave exactly the same for some very edge cases that are unlikely to happen, such as `OpenFile("/")`. These cases are marked red in the sheet. Implementing those edge cases will make the code too complicated but doesn't contribute much to the compatibility, and I feel like they can be even indeterminate and are "undefined behaviour" on real 3DS. If anyone wants citra to be more accurate, they can always add more error checks in the future.

Note that I didn't test `RenameFile` and `RenameDirectory`, and I keep the old error code. I want to leave this to the next PR, because they are another large topic.

You can also run the mentioned test program on citra with this PR to test. However, the program uses software keyboard to input commands, so you may want to merge [this commit](https://github.com/wwylele/citra/commit/0baf9f8fb6f0cd160d735c59d44a43d005539e2d) so that you can input commands from stdin.

Fixes TODO 2094, and "path boundary check" comments in TODO 2106.

Additional commits:
 - hwtested and implemented SDMC write-only archive. Should fixes TODO 1607.
 - rename `SaveDataCheck` archive to `NCCH` archive, according to [3dbrew](https://www.3dbrew.org/wiki/Filesystem_services#Archives) and its behaviour.

This PR is not widely test yet. Please help me test games to see if there is any regression! Please especially pay attention when game want to create a new save or delete the save.

---------------------

TODO:
 - [x] Fix logs
 - [x] Documentation
 - [x] Rename error descriptions
 - [x] Fix internal use of error code in other service

### CODE REVIEW

**Comment by Jhno591** [comment]
Nice, test is not really needed, cases non harmful test errors upon build.

**Comment by wwylele** [comment]
@Jhno591 Test _is_ needed. Actually before the last commit (which was added after your comment) this PR was failing many games to even boot (including Pokemon). It is not just as simple as "no error to build"

**Comment by Jhno591** [comment]
I know, is was the last one be for this one, just caused the input core with tests error

**Comment by Jhno591** [comment]
I think it's best to wait until your code more complete!

**Comment by Jhno591** [comment]
Could you check on the Input_core error ?, that only don't work with the tests, main build id fine.

**Comment by Dragios** [comment]
Something wrong on your side I guess. I can run Pokemon X/Y without save file with JIT turned off.

**Comment by Jhno591** [comment]
Dose it start a new game @Dragios ?, When you enter the window/door ?, I know the JIT issue just has white at that point, and without goes black

**Comment by wwylele** [comment]
@Jhno591 If you mean the existing freezing issue of XY intro, this PR is not mean to fix that, so it is expected that it still freeze.

**Comment by wwylele** [comment]
Anyway, this is in main repo now. Time to close

**Comment by Jhno591** [comment]
No wwylele to start a fresh game saving, ie new save

**Comment by wwylele** [comment]
@Jhno591 checked, and didn't find any regression against the master branch.

**Comment by Jhno591** [comment]
Ok thanks wwylele, It ok, Also try fresh game save in PM XY no go just black screens w your citra-fix-fs-err.zip build of, I guess its just having that audio issues as no Music are other, MerryMage has a big list of audio fixes, unsure of what one maybe of help any one know ? - https://github.com/MerryMage/citra/branches

**Pull request closed without merging**
