### PR TITLE
cec

### PR DESCRIPTION
**Pull request by wwylele**

### CODE REVIEW

**Comment by wwylele** [comment]
Status: partially functioning, but game can't create mailbox (observed game writing all-zero data to the mailbox?). If with a proper dump of cec save from 3DS (hint: 3dsfuse doesn't work), the mailbox info can show up in the system settings.

**Comment by valentinvanelslande** [comment]
https://github.com/wwylele/citra/pull/32/files#diff-d2afc43859454142b515894126f42f2cR162
super mario 3d land crashes when i enable streetpass

**Comment by valentinvanelslande** [comment]
Tomodachi Life Fatal Error + Loop after enabling StreetPass (Send Babies/Town Hall)
[ 46.491461] Service.ERR core/hle/service/err_f.cpp:ThrowFatalError:155: Fatal error
[ 46.491842] Service.ERR core/hle/service/err_f.cpp:ThrowFatalError:158: Fatal error type: Generic
[ 46.492557] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:135: PID: 0x0000000A
[ 46.494498] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:137: REV: 0x00000000_0x0000D798
[ 46.494902] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:139: TID: 0x00000000_0x00000000
[ 46.495049] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:141: AID: 0x00000000_0x00000000
[ 46.495969] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:142: ADR: 0x0013FD50
[ 46.497889] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:145: RSL: 0xC8804470
[ 46.498454] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:146: Level: 25
[ 46.498763] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:147: Summary: 4
[ 46.499092] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:148: Module: 17
[ 46.499968] Service.ERR core/hle/service/err_f.cpp:LogGenericInfo:149: Desc: 112
[ 46.500392] Service.ERR core/hle/service/err_f.cpp:ThrowFatalError:169: Datetime: 2018/01/19 16:42:35

**Comment by valentinvanelslande** [comment]
nintendogs + cats also crashes when enabling streetpass

**Comment by valentinvanelslande** [comment]
With AM ServiceFramework PR, build fails
Fix the build

**Comment by wwylele** [comment]
Closing as master branch has an alternative impl

**Pull request closed without merging**
